// iOS Table Handlers
export { handleBibleCodeColumn } from "./ios/BibleCode"
export { handleContainedByMediaLinkColumn } from "./ios/ContainedByMediaLink"
export { handleCountryColumn } from "./ios/Country"
export { handleCountryLinkColumn } from "./ios/CountryLink"
export { handleEtagColumn } from "./ios/Etag"
export { handleLanguageColumn } from "./ios/Language"
export { handleMediaCategoryColumn } from "./ios/MediaCategory"
export { handleMediaItemColumn } from "./ios/MediaItem"
export { handleReadingLanguageDataColumn } from "./ios/ReadingLanguageData"
export { handleSuggestedLanguageColumn } from "./ios/SuggestedLanguage"

// Android Table Handlers
export { handleCountriesColumn } from "./android/countries"
export { handleCountryTranslationsColumn } from "./android/country_translations"
export { handleMediaDataColumn } from "./android/media_data"
export { handleMediaLanguageLinksColumn } from "./android/media_language_links"
export { handleMediaLanguageTranslationsColumn } from "./android/media_language_translations"
export { handleMediaLanguagesColumn } from "./android/media_languages"
export { handleMediaMetadataColumn } from "./android/media_metadata"
export { handleReadingLanguagesColumn } from "./android/reading_languages"
export { handleRoomMasterTableColumn } from "./android/room_master_table"
export { handleSpokenLanguagesColumn } from "./android/spoken_languages"
export { handleSuggestedLanguagesColumn } from "./android/suggested_languages"
export { handleTermTranslationsColumn } from "./android/term_translations"
